// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using projFinal.Models;
using System;

namespace projFinal.Migrations
{
    [DbContext(typeof(projFinalContext))]
    [Migration("20180702181822_Locadora")]
    partial class Locadora
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("projFinal.Models.Borrow", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("userid");

                    b.HasKey("id");

                    b.HasIndex("userid");

                    b.ToTable("Borrows");
                });

            modelBuilder.Entity("projFinal.Models.Movie", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Borrowid");

                    b.Property<string>("name");

                    b.Property<int>("year");

                    b.HasKey("id");

                    b.HasIndex("Borrowid");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("projFinal.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("email");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("projFinal.Models.Borrow", b =>
                {
                    b.HasOne("projFinal.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("userid");
                });

            modelBuilder.Entity("projFinal.Models.Movie", b =>
                {
                    b.HasOne("projFinal.Models.Borrow")
                        .WithMany("movie")
                        .HasForeignKey("Borrowid");
                });
#pragma warning restore 612, 618
        }
    }
}
